import { StyleSheet } from 'react-native';

const styles: any = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#f5f5f5',
      flexDirection: 'column',
      alignItems: 'flex-start',
      justifyContent: 'flex-start',
      width: '100%',
    },
    inputContainer: {
    //   borderBottomColor: '#F5FCFF',
      backgroundColor: 'gray',
      borderRadius: 30,
    //   borderBottomWidth: 0,
      width: 250,
      height: 45,
      marginBottom: 20,
      flexDirection: 'row',
      alignItems: 'flex-start',
    },
    inputs: {
        height: 45,
        marginLeft: 16,
        // borderBottomColor: '#FFFFFF',
        flex: 1,
    },
    inputIcon: {
      width: 30,
      height: 30,
      marginLeft: 15,
      justifyContent: 'center',
    },
    loginText: {
      color: 'white',
    },
    imageContainer: {
      marginBottom: 20,
      padding: 10,
    },
    imageLogo: {
      width: 350,
      height: 250,
    },
    itemLeft: {
      // flexGrow: 1,
      // marginLeft: 10,
      // width: 100,
    },
    itemRight: {
      // width: 250,
      backgroundColor: 'white',
      borderRadius: 30,
      width: 200,
      height: 45,
      // marginLeft: 10,
      paddingLeft: 20,
    },
    itemRight2: {
      // width: 250,
      backgroundColor: 'white',
      borderRadius: 30,
      width: '100%',
      height: 200,
      marginTop: 10,
      paddingLeft: 20,
      flex: 1,
    },
    card1: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      width: '100%',
      justifyContent: 'space-between',
      paddingHorizontal: 10,
      paddingVertical: 10,
      borderBottomColor: '#CFD8DC',
      borderBottomWidth: 1,
      flexGrow: 0,
    },
    card2: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      width: '100%',
      justifyContent: 'center',
      padding: 10,
      margin: 10,
      // borderBottomColor: '#CFD8DC',
      // borderBottomWidth: 1,
      // flexGrow: 0,
    },
    card3: {
      flex: 1,
      flexDirection: 'column',
      alignItems: 'flex-start',
      width: '100%',
      justifyContent: 'flex-start',
      paddingHorizontal: 10,
      paddingVertical: 10,
      // height: 200,
      borderBottomColor: '#CFD8DC',
      borderBottomWidth: 1,
      // flexGrow: 0,
      // backgroundColor: 'yellow',
    },
    card4: {
      backgroundColor: '#ffe082',
      paddingVertical: 10,
      paddingHorizontal: 15,
      borderRadius: 15,
      alignItems: 'flex-start',
      // width: '100%',
      margin: 10,
      flex: 1,
    },
    textInfo: {
      fontSize: 18,
      marginTop: 20,
      color: '#696969',
    },
    textSmallInfo: {
      fontSize: 14,
      color: '#696969',
      marginBottom: 10,
    },
    largeTextInfo: {
      fontSize: 16,
      color: '#000000',
      marginBottom: 4,
      fontWeight: 'bold',
    },
    buttonContainer: {
      // height: 50,
      paddingVertical: 10,
      paddingHorizontal: 20,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 10,
      // width: 220,
      borderRadius: 30,
    },
    loginButton: {
      backgroundColor: '#1976d2',
    },
    buttonText: {
      fontSize: 20,
      fontWeight: 'bold',
      // marginBottom: 10,
      color: '#ffffff',
    },
    buttonContainerDisabled: {
      // height: 50,
      paddingVertical: 10,
      paddingHorizontal: 20,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 10,
      // width: 220,
      borderRadius: 30,
    },
    loginButtonDisabled: {
      backgroundColor: '#e0e0e0',
    },
    buttonTextDisabled: {
      fontSize: 20,
      fontWeight: 'bold',
      // marginBottom: 10,
      color: '#aeaeae',
    },
    avatar: {
      width: 300,
      height: 400,
      borderRadius: 5,
      borderWidth: 2,
      borderColor: 'white',
      marginBottom: 5,
      backgroundColor: 'white',
    },
  });

export default styles;
