import { StyleSheet } from 'react-native';

const styles: any = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#f5f5f5',
      flexDirection: 'column',
      alignItems: 'flex-start',
      justifyContent: 'flex-start',
      width: '100%',
    },
    inputContainer: {
    //   borderBottomColor: '#F5FCFF',
      backgroundColor: 'gray',
      borderRadius: 30,
    //   borderBottomWidth: 0,
      width: 250,
      height: 45,
      marginBottom: 20,
      flexDirection: 'row',
      alignItems: 'flex-start',
    },
    inputs: {
        height: 45,
        marginLeft: 16,
        // borderBottomColor: '#FFFFFF',
        flex: 1,
    },
    inputIcon: {
      width: 30,
      height: 30,
      marginLeft: 15,
      justifyContent: 'center',
    },
    buttonContainer: {
      height: 45,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 10,
      width: 200,
      borderRadius: 30,
    },
    loginButton: {
      backgroundColor: '#00b5ec',
    },
    loginText: {
      color: 'white',
    },
    imageContainer: {
      marginBottom: 20,
      padding: 10,
    },
    imageLogo: {
      width: 350,
      height: 250,
    },
    itemLeft: {
      // flexGrow: 1,
      // marginLeft: 10,
      // width: 100,
    },
    itemRight: {
      // width: 250,
      backgroundColor: 'white',
      borderRadius: 30,
      width: 200,
      height: 45,
      // marginLeft: 10,
      paddingLeft: 20,
    },
    itemRight2: {
      // width: 250,
      backgroundColor: 'white',
      borderRadius: 30,
      width: '100%',
      height: 200,
      marginTop: 10,
      paddingLeft: 20,
      flex: 1,
    },
    card1: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      width: '100%',
      justifyContent: 'space-between',
      paddingHorizontal: 10,
      paddingVertical: 40,
      borderBottomColor: '#CFD8DC',
      borderBottomWidth: 1,
      flexGrow: 0,
    },
    card2: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      width: '100%',
      justifyContent: 'center',
      padding: 30,
      margin: 10,
      // borderBottomColor: '#CFD8DC',
      // borderBottomWidth: 1,
      // flexGrow: 0,
    },
    card3: {
      flex: 1,
      flexDirection: 'column',
      alignItems: 'flex-start',
      width: '100%',
      justifyContent: 'flex-start',
      paddingHorizontal: 10,
      paddingVertical: 10,
      // height: 200,
      borderBottomColor: '#CFD8DC',
      borderBottomWidth: 1,
      // flexGrow: 0,
      // backgroundColor: 'yellow',
    },
  });

export default styles;
